name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ampolic/ampolic-core/.github/workflows/site-ci.yml@main
    with:
      node-version: '22'
    secrets:
      packages-token: ${{ secrets.PACKAGES_TOKEN }}
